### ISSUE TITLE
BPM and measure mismatch

### ISSUE THREAD

**Issue by tpvidigal** [akiomik/dtx2midi#3]
Hi again, @akiomik :)
I successfully generated the MIDI file of the music 008 from the DTX file.
However, when I opened with MuseScore, I noticed that the note values were doubled (a half note was placed were a quarter note was expected, for example).
I tried to run with music 002 and noticed that the same doubled value notes were present. Not only that, the BPM was annotated as 120 instead of  84 (the value at the DTX's header). It seems that your program is always using 120 BPM.

I added the source DTX files and generated MIDIs of both songs: 
[bug_sample.zip](https://github.com/akiomik/dtx2midi/files/5013479/bug_sample.zip)

PS: Also noticed that the music 002 was generated with the notes displaced by 1 half note earlier, but  guess it's a detail of DTX file and is very easily fixed manually :)

**Comment by akiomik** [comment]
Thanks for reporting the issue 😄 

I fixed the bpm problem for 002 in this commit https://github.com/akiomik/dtx2midi/commit/98d40e499eb6d998b803a35e363b060c5b5a5b6e.
And it seemed to be fine from what I've listen. (I used a VLC player.) [002_healing_day_ext.midi.zip](https://github.com/akiomik/dtx2midi/files/5045749/002_healing_day_ext.midi.zip)

But there is still a problem with MuseScore.
I don't know if this is a problem with MuseScore, this program, or the Haskore I use on the back end.

**Comment by akiomik** [comment]
> But there is still a problem with MuseScore.
> I don't know if this is a problem with MuseScore, this program, or the Haskore I use on the back end.

Instead of headers being parsed correctly, a score is now incorrectly rendered 😨 
The problem seems to be caused by Haskore. I checked the generated MIDI data and found that the BPM is fixed at 120 and only the timing data of the notes changes.

For now, the workaround for rendering it correctly as a score is to change the BPM of the DTX file to 120.

### MIDI file generated at 84 BPM

<img width="929" alt="スクリーンショット 2020-08-13 7 01 49" src="https://user-images.githubusercontent.com/1457682/90072913-375af580-dd33-11ea-9e23-96b8e6ba864f.png">

### MIDI file generated at 120 BPM

<img width="898" alt="スクリーンショット 2020-08-13 7 02 10" src="https://user-images.githubusercontent.com/1457682/90072914-39bd4f80-dd33-11ea-9d27-98bd6b813439.png">

**Comment by tpvidigal** [comment]
Oh god... is one of those Hahaha
But yeah... For my case the midi generated with BPM 120 is the ideal one, but I don't what you think is the best option

**Comment by akiomik** [comment]
Now I fixed a bug about global BPM in [this commit](https://github.com/akiomik/dtx2midi/commit/dffb472321aa8351d1a09b3c859b2407a815c9b9) 🎉 

### Musescore screenshot

<img width="725" alt="スクリーンショット 2020-08-17 18 47 06" src="https://user-images.githubusercontent.com/1457682/90383098-a2e9ed80-e0ba-11ea-8c84-9fa158892835.png">
